// REV 002/24JUN26 - Flagpedia CDN eklendi (flagcdn.com - guncel bayraklar)
// [code, name_tr, name_en] - unicode ve URL runtime'da hesaplaniyor

const FLAG_CDN = "https://flagcdn.com/w320";

const _BASE = [
  ["AD","Andorra","Andorra"],
  ["AE","Birleşik Arap Emirlikleri","United Arab Emirates"],
  ["AF","Afganistan","Afghanistan"],
  ["AG","Antigua ve Barbuda","Antigua and Barbuda"],
  ["AI","Anguilla","Anguilla"],
  ["AL","Arnavutluk","Albania"],
  ["AM","Ermenistan","Armenia"],
  ["AO","Angola","Angola"],
  ["AQ","Antarktika","Antarctica"],
  ["AR","Arjantin","Argentina"],
  ["AS","Amerikan Samoası","American Samoa"],
  ["AT","Avusturya","Austria"],
  ["AU","Avustralya","Australia"],
  ["AW","Aruba","Aruba"],
  ["AX","Aland Adaları","Aland Islands"],
  ["AZ","Azerbaycan","Azerbaijan"],
  ["BA","Bosna-Hersek","Bosnia and Herzegovina"],
  ["BB","Barbados","Barbados"],
  ["BD","Bangladeş","Bangladesh"],
  ["BE","Belçika","Belgium"],
  ["BF","Burkina Faso","Burkina Faso"],
  ["BG","Bulgaristan","Bulgaria"],
  ["BH","Bahreyn","Bahrain"],
  ["BI","Burundi","Burundi"],
  ["BJ","Benin","Benin"],
  ["BL","Saint Barthélemy","Saint Barthelemy"],
  ["BM","Bermuda","Bermuda"],
  ["BN","Brunei","Brunei"],
  ["BO","Bolivya","Bolivia"],
  ["BQ","Karayip Hollandası","Caribbean Netherlands"],
  ["BR","Brezilya","Brazil"],
  ["BS","Bahamalar","Bahamas"],
  ["BT","Butan","Bhutan"],
  ["BV","Bouvet Adası","Bouvet Island"],
  ["BW","Botsvana","Botswana"],
  ["BY","Belarus","Belarus"],
  ["BZ","Belize","Belize"],
  ["CA","Kanada","Canada"],
  ["CC","Cocos Adaları","Cocos Islands"],
  ["CD","Kongo Demokratik Cumhuriyeti","DR Congo"],
  ["CF","Orta Afrika Cumhuriyeti","Central African Republic"],
  ["CG","Kongo Cumhuriyeti","Republic of the Congo"],
  ["CH","İsviçre","Switzerland"],
  ["CI","Fildişi Sahili","Ivory Coast"],
  ["CK","Cook Adaları","Cook Islands"],
  ["CL","Şili","Chile"],
  ["CM","Kamerun","Cameroon"],
  ["CN","Çin","China"],
  ["CO","Kolombiya","Colombia"],
  ["CR","Kosta Rika","Costa Rica"],
  ["CU","Küba","Cuba"],
  ["CV","Yeşil Burun Adaları","Cape Verde"],
  ["CW","Curaçao","Curacao"],
  ["CX","Christmas Adası","Christmas Island"],
  ["CY","Kıbrıs","Cyprus"],
  ["CZ","Çekya","Czech Republic"],
  ["DE","Almanya","Germany"],
  ["DJ","Cibuti","Djibouti"],
  ["DK","Danimarka","Denmark"],
  ["DM","Dominika","Dominica"],
  ["DO","Dominik Cumhuriyeti","Dominican Republic"],
  ["DZ","Cezayir","Algeria"],
  ["EC","Ekvador","Ecuador"],
  ["EE","Estonya","Estonia"],
  ["EG","Mısır","Egypt"],
  ["EH","Batı Sahra","Western Sahara"],
  ["ER","Eritre","Eritrea"],
  ["ES","İspanya","Spain"],
  ["ET","Etiyopya","Ethiopia"],
  ["FI","Finlandiya","Finland"],
  ["FJ","Fiji","Fiji"],
  ["FK","Falkland Adaları","Falkland Islands"],
  ["FM","Mikronezya","Micronesia"],
  ["FO","Faroe Adaları","Faroe Islands"],
  ["FR","Fransa","France"],
  ["GA","Gabon","Gabon"],
  ["GB","Birleşik Krallık","United Kingdom"],
  ["GD","Grenada","Grenada"],
  ["GE","Gürcistan","Georgia"],
  ["GF","Fransız Guyanası","French Guiana"],
  ["GG","Guernsey","Guernsey"],
  ["GH","Gana","Ghana"],
  ["GI","Cebelitarık","Gibraltar"],
  ["GL","Grönland","Greenland"],
  ["GM","Gambiya","Gambia"],
  ["GN","Gine","Guinea"],
  ["GP","Guadeloupe","Guadeloupe"],
  ["GQ","Ekvator Ginesi","Equatorial Guinea"],
  ["GR","Yunanistan","Greece"],
  ["GS","Güney Georgia","South Georgia"],
  ["GT","Guatemala","Guatemala"],
  ["GU","Guam","Guam"],
  ["GW","Gine-Bissau","Guinea-Bissau"],
  ["GY","Guyana","Guyana"],
  ["HK","Hong Kong","Hong Kong"],
  ["HM","Heard Adası","Heard Island"],
  ["HN","Honduras","Honduras"],
  ["HR","Hırvatistan","Croatia"],
  ["HT","Haiti","Haiti"],
  ["HU","Macaristan","Hungary"],
  ["ID","Endonezya","Indonesia"],
  ["IE","İrlanda","Ireland"],
  ["IL","İsrail","Israel"],
  ["IM","Man Adası","Isle of Man"],
  ["IN","Hindistan","India"],
  ["IO","Britanya Hint Okyanusu Toprakları","British Indian Ocean Territory"],
  ["IQ","Irak","Iraq"],
  ["IR","İran","Iran"],
  ["IS","İzlanda","Iceland"],
  ["IT","İtalya","Italy"],
  ["JE","Jersey","Jersey"],
  ["JM","Jamaika","Jamaica"],
  ["JO","Ürdün","Jordan"],
  ["JP","Japonya","Japan"],
  ["KE","Kenya","Kenya"],
  ["KG","Kırgızistan","Kyrgyzstan"],
  ["KH","Kamboçya","Cambodia"],
  ["KI","Kiribati","Kiribati"],
  ["KM","Komorlar","Comoros"],
  ["KN","Saint Kitts ve Nevis","Saint Kitts and Nevis"],
  ["KP","Kuzey Kore","North Korea"],
  ["KR","Güney Kore","South Korea"],
  ["KW","Kuveyt","Kuwait"],
  ["KY","Cayman Adaları","Cayman Islands"],
  ["KZ","Kazakistan","Kazakhstan"],
  ["LA","Laos","Laos"],
  ["LB","Lübnan","Lebanon"],
  ["LC","Saint Lucia","Saint Lucia"],
  ["LI","Lihtenştayn","Liechtenstein"],
  ["LK","Sri Lanka","Sri Lanka"],
  ["LR","Liberya","Liberia"],
  ["LS","Lesoto","Lesotho"],
  ["LT","Litvanya","Lithuania"],
  ["LU","Lüksemburg","Luxembourg"],
  ["LV","Letonya","Latvia"],
  ["LY","Libya","Libya"],
  ["MA","Fas","Morocco"],
  ["MC","Monako","Monaco"],
  ["MD","Moldova","Moldova"],
  ["ME","Karadağ","Montenegro"],
  ["MF","Saint Martin","Saint Martin"],
  ["MG","Madagaskar","Madagascar"],
  ["MH","Marshall Adaları","Marshall Islands"],
  ["MK","Kuzey Makedonya","North Macedonia"],
  ["ML","Mali","Mali"],
  ["MM","Myanmar","Myanmar"],
  ["MN","Moğolistan","Mongolia"],
  ["MO","Makao","Macao"],
  ["MP","Kuzey Mariana Adaları","Northern Mariana Islands"],
  ["MQ","Martinik","Martinique"],
  ["MR","Moritanya","Mauritania"],
  ["MS","Montserrat","Montserrat"],
  ["MT","Malta","Malta"],
  ["MU","Mauritius","Mauritius"],
  ["MV","Maldivler","Maldives"],
  ["MW","Malavi","Malawi"],
  ["MX","Meksika","Mexico"],
  ["MY","Malezya","Malaysia"],
  ["MZ","Mozambik","Mozambique"],
  ["NA","Namibya","Namibia"],
  ["NC","Yeni Kaledonya","New Caledonia"],
  ["NE","Nijer","Niger"],
  ["NF","Norfolk Adası","Norfolk Island"],
  ["NG","Nijerya","Nigeria"],
  ["NI","Nikaragua","Nicaragua"],
  ["NL","Hollanda","Netherlands"],
  ["NO","Norveç","Norway"],
  ["NP","Nepal","Nepal"],
  ["NR","Nauru","Nauru"],
  ["NU","Niue","Niue"],
  ["NZ","Yeni Zelanda","New Zealand"],
  ["OM","Umman","Oman"],
  ["PA","Panama","Panama"],
  ["PE","Peru","Peru"],
  ["PF","Fransız Polinezyası","French Polynesia"],
  ["PG","Papua Yeni Gine","Papua New Guinea"],
  ["PH","Filipinler","Philippines"],
  ["PK","Pakistan","Pakistan"],
  ["PL","Polonya","Poland"],
  ["PM","Saint Pierre ve Miquelon","Saint Pierre and Miquelon"],
  ["PN","Pitcairn Adaları","Pitcairn Islands"],
  ["PR","Porto Riko","Puerto Rico"],
  ["PS","Filistin","Palestine"],
  ["PT","Portekiz","Portugal"],
  ["PW","Palau","Palau"],
  ["PY","Paraguay","Paraguay"],
  ["QA","Katar","Qatar"],
  ["RE","Réunion","Reunion"],
  ["RO","Romanya","Romania"],
  ["RS","Sırbistan","Serbia"],
  ["RU","Rusya","Russia"],
  ["RW","Ruanda","Rwanda"],
  ["SA","Suudi Arabistan","Saudi Arabia"],
  ["SB","Solomon Adaları","Solomon Islands"],
  ["SC","Seyşeller","Seychelles"],
  ["SD","Sudan","Sudan"],
  ["SE","İsveç","Sweden"],
  ["SG","Singapur","Singapore"],
  ["SH","Saint Helena","Saint Helena"],
  ["SI","Slovenya","Slovenia"],
  ["SJ","Svalbard ve Jan Mayen","Svalbard and Jan Mayen"],
  ["SK","Slovakya","Slovakia"],
  ["SL","Sierra Leone","Sierra Leone"],
  ["SM","San Marino","San Marino"],
  ["SN","Senegal","Senegal"],
  ["SO","Somali","Somalia"],
  ["SR","Surinam","Suriname"],
  ["SS","Güney Sudan","South Sudan"],
  ["ST","Sao Tome ve Principe","Sao Tome and Principe"],
  ["SV","El Salvador","El Salvador"],
  ["SX","Sint Maarten","Sint Maarten"],
  ["SY","Suriye","Syria"],
  ["SZ","Esvatini","Eswatini"],
  ["TC","Turks ve Caicos Adaları","Turks and Caicos Islands"],
  ["TD","Çad","Chad"],
  ["TF","Fransız Güney Toprakları","French Southern Territories"],
  ["TG","Togo","Togo"],
  ["TH","Tayland","Thailand"],
  ["TJ","Tacikistan","Tajikistan"],
  ["TK","Tokelau","Tokelau"],
  ["TL","Doğu Timor","Timor-Leste"],
  ["TM","Türkmenistan","Turkmenistan"],
  ["TN","Tunus","Tunisia"],
  ["TO","Tonga","Tonga"],
  ["TR","Türkiye","Turkey"],
  ["TT","Trinidad ve Tobago","Trinidad and Tobago"],
  ["TV","Tuvalu","Tuvalu"],
  ["TW","Tayvan","Taiwan"],
  ["TZ","Tanzanya","Tanzania"],
  ["UA","Ukrayna","Ukraine"],
  ["UG","Uganda","Uganda"],
  ["UM","ABD Uzak Adaları","US Minor Outlying Islands"],
  ["US","Amerika Birleşik Devletleri","United States"],
  ["UY","Uruguay","Uruguay"],
  ["UZ","Özbekistan","Uzbekistan"],
  ["VA","Vatikan","Vatican City"],
  ["VC","Saint Vincent ve Grenadinler","Saint Vincent and the Grenadines"],
  ["VE","Venezuela","Venezuela"],
  ["VG","Britanya Virjin Adaları","British Virgin Islands"],
  ["VI","ABD Virjin Adaları","US Virgin Islands"],
  ["VN","Vietnam","Vietnam"],
  ["VU","Vanuatu","Vanuatu"],
  ["WF","Wallis ve Futuna","Wallis and Futuna"],
  ["WS","Samoa","Samoa"],
  ["XK","Kosova","Kosovo"],
  ["YE","Yemen","Yemen"],
  ["YT","Mayotte","Mayotte"],
  ["ZA","Güney Afrika","South Africa"],
  ["ZM","Zambiya","Zambia"],
  ["ZW","Zimbabve","Zimbabwe"],
];

function _cp(code) {
  return [
    (0x1F1E6 + code.charCodeAt(0) - 65).toString(16),
    (0x1F1E6 + code.charCodeAt(1) - 65).toString(16),
  ];
}

export const BAYRAKLAR = _BASE.map(([code, name, name_en]) => {
  const cps = _cp(code);
  return {
    code,
    name,
    name_en,
    emoji: String.fromCodePoint(parseInt(cps[0], 16), parseInt(cps[1], 16)),
    unicode: cps.join("-"),
    twemoji_url: `https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/72x72/${cps.join("-")}.png`,
    flagpedia_url: `${FLAG_CDN}/${code.toLowerCase()}.png`,
  };
});
